[package]
name = "epoxy-client"
version = "3.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hyper = { version = "1.6.0", features = ["client", "http1"] }
hyper-util-wasm = { git = "https://github.com/r58Playz/hyper-util-wasm", rev = "c582f05daa6529a75f6838a26ebf29ff09f62921", features = ["client-legacy", "http1"] }
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }
tower = { version = "0.4.13", features = ["util"] }
thiserror = "2.0.12"
wisp-mux = { version = "6.0.0", path = "../wisp" }
bytes = "1.10.1"
pin-project = "1.1.10"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.91"
js-sys = "0.3.91"
wasm-bindgen = "0.2.114"
wasm-streams = "0.4.2"
webpki-roots = "1.0.0"
futures-rustls = { version = "0.26.0", default-features = false, features = ["tls12", "ring"] }
http-body-util = "0.1.3"
http = "1.3.1"
http-body = "1.0.1"
async-trait = "0.1.89"

[features]
debug = []

[dependencies.ring]
version = "*"
features = ["wasm32_unknown_unknown_js"]

[dependencies.rustls-pki-types]
version = "*"
features = ["web"]

[dependencies.instant]
version = "*"
features = ["wasm-bindgen"]
