[package]
name = "epoxy-server"
version = "2.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.86"
async-speed-limit = { version = "0.4.2", optional = true, features = ["tokio"] }
async-trait = "0.1.81"
base64 = "0.22.1"
bytes = "1.7.1"
cfg-if = "1.0.0"
clap = { version = "4.5.16", features = ["cargo", "derive"] }
console-subscriber = { version = "0.5.0", optional = true }
ed25519-dalek = { version = "2.1.1", features = ["pem"] }
env_logger = "0.11.5"
event-listener = "5.3.1"
fast-socks5 = "1.0.0"
futures-util = "0.3.30"
hickory-resolver = "0.26.1"
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.7", features = ["tokio"] }
lazy_static = "1.5.0"
libc = { version = "0.2.158", optional = true }
log = { version = "0.4.22", features = ["serde", "std"] }
nix = { version = "0.31.3", features = ["term"] }
pin-project-lite = "0.2.15"
pty-process = { version = "0.4.0", features = ["async", "tokio"], optional = true }
regex = "1.10.6"
rustls-pemfile = "2.1.3"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
serde_yaml = { version = "0.9.34", optional = true }
sha1 = "0.11.0"
sha2 = "0.11.0"
shell-words = { version = "1.1.0", optional = true }
tikv-jemalloc-ctl = { version = "0.6.0", features = ["stats", "use_std"] }
tikv-jemallocator = "0.6.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-rustls = { version = "0.26.0", features = ["ring", "tls12"], default-features = false }
tokio-util = { version = "0.7.11", features = ["codec", "compat", "io-util", "net"] }
tokio-websockets = { version = "0.13.2", features = ["server", "sha1_smol"] }
toml = { version = "1.1.2", optional = true }
uuid = { version = "1.10.0", features = ["v4"] }
wisp-mux = { version = "*", path = "../wisp", features = ["tokio-websockets", "certificate"] }

[features]
default = ["toml"]

yaml = ["dep:serde_yaml"]
toml = ["dep:toml"]

twisp = ["dep:pty-process", "dep:libc", "dep:shell-words"]
speed-limit = ["dep:async-speed-limit"]
tokio-console = ["dep:console-subscriber"]

[build-dependencies]
vergen-git2 = { version = "9.1.0", features = ["rustc"] }
