name: Epoxy Server

on:
  push:
    branches:
      - multiplexed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: epoxy-server
          path: target/release/epoxy-server

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/multiplexed'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: epoxy-server
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: epoxy-server
          tag_name: latest
          name: Latest
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
